window.QUESTION_BANK = {
  easy: [
    {
      q: "Onde Jesus nasceu?",
      a: ["Nazaré", "Belém", "Jerusalém", "Cafarnaum"],
      c: 1,
      tip: "A cidade do nascimento está ligada à linhagem de Davi.",
      verse: "Lucas 2:4-7",
    },
    {
      q: "Quem foi a mãe de Jesus?",
      a: ["Marta", "Maria", "Isabel", "Rute"],
      c: 1,
      tip: "O anúncio veio por um anjo no início do Evangelho de Lucas.",
      verse: "Lucas 1:26-31",
    },
    {
      q: "Quantos discípulos (apóstolos) Jesus escolheu de forma especial?",
      a: ["7", "10", "12", "70"],
      c: 2,
      tip: "Esse número aparece repetidamente nas listas apostólicas.",
      verse: "Marcos 3:14-15",
    },
    {
      q: "Qual era a profissão de Pedro antes de seguir Jesus?",
      a: ["Carpinteiro", "Pescador", "Médico", "Soldado"],
      c: 1,
      tip: "Ele trabalhava com redes quando foi chamado.",
      verse: "Mateus 4:18-19",
    },
    {
      q: "Em que rio Jesus foi batizado?",
      a: ["Nilo", "Eufrates", "Jordão", "Tigre"],
      c: 2,
      tip: "É um rio muito citado em cenas de João Batista.",
      verse: "Mateus 3:13",
    },
    {
      q: "Qual foi o primeiro milagre de Jesus, segundo o Evangelho de João?",
      a: ["Multiplicação dos pães", "Cura do cego", "Água em vinho", "Acalmar a tempestade"],
      c: 2,
      tip: "Aconteceu em um casamento.",
      verse: "João 2:1-11",
    },
    {
      q: "Quem batizou Jesus?",
      a: ["Pedro", "João Batista", "André", "Tiago"],
      c: 1,
      tip: "É a figura central do início do ministério público de Jesus.",
      verse: "Mateus 3:13-15",
    },
    {
      q: "Qual era a profissão de José, pai adotivo de Jesus?",
      a: ["Carpinteiro", "Pescador", "Pastor", "Agricultor"],
      c: 0,
      tip: "Muitas traduções usam um termo ligado a trabalho manual/artesão.",
      verse: "Mateus 13:55",
    },
    {
      q: "Quantos dias Jesus jejuou no deserto?",
      a: ["7 dias", "30 dias", "40 dias", "50 dias"],
      c: 2,
      tip: "É o mesmo número marcante em vários episódios bíblicos.",
      verse: "Mateus 4:2",
    },
    {
      q: "Quem negou Jesus três vezes antes do galo cantar?",
      a: ["João", "Pedro", "Judas", "Tiago"],
      c: 1,
      tip: "Um discípulo muito próximo, conhecido por agir por impulso.",
      verse: "Mateus 26:69-75",
    },
    {
      q: "Quantos Evangelhos existem na Bíblia?",
      a: ["2", "3", "4", "5"],
      c: 2,
      tip: "São quatro relatos principais sobre a vida de Jesus.",
      verse: "Mateus, Marcos, Lucas e João",
    },
    {
      q: "Em que cidade Jesus cresceu?",
      a: ["Belém", "Nazaré", "Cafarnaum", "Jerusalém"],
      c: 1,
      tip: "Fica na Galileia e deu origem a um apelido famoso de Jesus.",
      verse: "Lucas 2:39-40",
    },
    {
      q: "Quem anunciou a Maria que ela seria mãe de Jesus?",
      a: ["Anjo Miguel", "Anjo Rafael", "Anjo Gabriel", "Um profeta"],
      c: 2,
      tip: "O mesmo mensageiro aparece em outras cenas importantes no Novo Testamento.",
      verse: "Lucas 1:26-27",
    },
    {
      q: "O que os magos levaram para Jesus?",
      a: ["Ouro, incenso e sal", "Ouro, incenso e mirra", "Prata, óleo e mirra", "Bronze, incenso e azeite"],
      c: 1,
      tip: "Foram três presentes clássicos e simbólicos.",
      verse: "Mateus 2:11",
    },
    {
      q: "Quantos anos Jesus tinha quando começou seu ministério?",
      a: ["20 anos", "25 anos", "30 anos", "35 anos"],
      c: 2,
      tip: "O texto diz “cerca de…”.",
      verse: "Lucas 3:23",
    },
    {
      q: "Qual foi o mandamento que Jesus deu aos seus discípulos em João 13:34?",
      a: ["Não roubar", "Amar uns aos outros", "Guardar o sábado", "Honrar pai e mãe"],
      c: 1,
      tip: "É chamado por Jesus de “novo mandamento”.",
      verse: "João 13:34",
    },
    {
      q: "Quem ajudou Jesus a carregar a cruz?",
      a: ["João", "Pedro", "Simão Cireneu", "José de Arimateia"],
      c: 2,
      tip: "Era um homem vindo de outra região, citado pelo lugar de origem.",
      verse: "Marcos 15:21",
    },
    {
      q: "Complete: 'Eu sou o pão da ___'.",
      a: ["Vida", "Verdade", "Luz", "Salvação"],
      c: 0,
      tip: "É uma das declarações “Eu sou” no Evangelho de João.",
      verse: "João 6:35",
    },
    {
      q: "Quem foi o primeiro mártir cristão?",
      a: ["Pedro", "Paulo", "Estêvão", "Tiago"],
      c: 2,
      tip: "Seu relato está em Atos, antes da conversão de Paulo dominar a narrativa.",
      verse: "Atos 7:54-60",
    },
    {
      q: "Em que animal Jesus entrou em Jerusalém?",
      a: ["Cavalo", "Camelo", "Jumento", "Boi"],
      c: 2,
      tip: "É um símbolo de humildade ligado a uma profecia.",
      verse: "Mateus 21:1-7",
    },
  ],

  medium: [
    {
      q: "Qual oração Jesus ensinou aos discípulos?",
      a: ["Salmo 23", "Pai Nosso", "Credo", "Shema Israel"],
      c: 1,
      tip: "Começa com uma invocação ao Pai.",
      verse: "Mateus 6:9-13",
    },
    {
      q: "Qual destes foi um discípulo que Jesus chamou enquanto trabalhava como cobrador de impostos?",
      a: ["Mateus", "Tomé", "Tiago", "Bartolomeu"],
      c: 0,
      tip: "Também é chamado de Levi em alguns textos.",
      verse: "Mateus 9:9",
    },
    {
      q: "Quantos pães e peixes foram citados no milagre da multiplicação para 5 mil homens?",
      a: ["3 pães e 2 peixes", "5 pães e 2 peixes", "7 pães e 3 peixes", "12 pães e 1 peixe"],
      c: 1,
      tip: "O relato menciona um número pequeno de comida para uma multidão.",
      verse: "João 6:9",
    },
    {
      q: "Em qual cidade Jesus realizou o milagre de transformar água em vinho?",
      a: ["Caná", "Belém", "Jericó", "Tiro"],
      c: 0,
      tip: "Fica na Galileia e aparece no início de João.",
      verse: "João 2:1-11",
    },
    {
      q: "Qual foi o sermão mais famoso de Jesus?",
      a: ["Sermão da Planície", "Sermão do Monte", "Sermão do Templo", "Sermão da Sinagoga"],
      c: 1,
      tip: "É onde estão as bem-aventuranças em Mateus.",
      verse: "Mateus 5–7",
    },
    {
      q: "Quem traiu Jesus por 30 moedas de prata?",
      a: ["Pedro", "Judas Iscariotes", "Tomé", "Mateus"],
      c: 1,
      tip: "Seu nome ficou associado à traição no imaginário cristão.",
      verse: "Mateus 26:14-16",
    },
    {
      q: "Quantas cestas sobraram após a multiplicação dos pães (5 mil)?",
      a: ["5 cestas", "7 cestas", "12 cestas", "20 cestas"],
      c: 2,
      tip: "O número coincide com algo muito simbólico em Israel.",
      verse: "Mateus 14:20",
    },
    {
      q: "Qual era o nome da irmã de Marta que se sentou aos pés de Jesus?",
      a: ["Maria", "Isabel", "Salomé", "Joana"],
      c: 0,
      tip: "Ela é citada no episódio das duas irmãs.",
      verse: "Lucas 10:38-39",
    },
    {
      q: "Jesus acalmou uma tempestade em qual mar?",
      a: ["Mar Morto", "Mar Mediterrâneo", "Mar da Galileia", "Mar Vermelho"],
      c: 2,
      tip: "É um lago/mar interno muito ligado ao ministério na Galileia.",
      verse: "Marcos 4:35-39",
    },
    {
      q: "Qual era o nome do cego que Jesus curou em Jericó?",
      a: ["Zaqueu", "Bartimeu", "Lázaro", "Simão"],
      c: 1,
      tip: "Ele gritava à beira do caminho chamando Jesus de “Filho de Davi”.",
      verse: "Marcos 10:46",
    },
    {
      q: "Qual era a idade de Jesus quando seus pais o encontraram no templo?",
      a: ["10 anos", "12 anos", "15 anos", "18 anos"],
      c: 1,
      tip: "É a única cena da infância de Jesus com fala registrada nos evangelhos.",
      verse: "Lucas 2:41-42",
    },
    {
      q: "Quem pediu a cabeça de João Batista?",
      a: ["Salomé", "Herodias", "Pilatos", "Herodes"],
      c: 0,
      tip: "O pedido aconteceu após uma apresentação diante de Herodes.",
      verse: "Marcos 6:22-25",
    },
    {
      q: "Qual discípulo é lembrado por ter duvidado da ressurreição até ver Jesus?",
      a: ["Pedro", "Tomé", "Judas", "Filipe"],
      c: 1,
      tip: "Ele queria provas concretas antes de crer.",
      verse: "João 20:24-25",
    },
    {
      q: "Quem foi o governador romano que condenou Jesus?",
      a: ["Herodes", "César", "Pôncio Pilatos", "Tibério"],
      c: 2,
      tip: "Ele lavou as mãos em um gesto simbólico no relato de Mateus.",
      verse: "Mateus 27:2",
    },
    {
      q: "Quantos discípulos Jesus enviou de dois em dois para pregar?",
      a: ["12", "40", "70", "100"],
      c: 2,
      tip: "Algumas traduções registram 72; aqui adotamos 70.",
      verse: "Lucas 10:1",
    },
    {
      q: "Em qual jardim Jesus orou antes de ser preso?",
      a: ["Jardim do Éden", "Jardim de Getsêmani", "Jardim de José", "Jardim do Templo"],
      c: 1,
      tip: "O local fica no Monte das Oliveiras.",
      verse: "Mateus 26:36",
    },
    {
      q: "Quem preparou o corpo de Jesus para o sepultamento, segundo João?",
      a: ["Pedro e João", "José de Arimateia e Nicodemos", "Maria e Marta", "Os soldados romanos"],
      c: 1,
      tip: "Um deles pediu o corpo a Pilatos; o outro levou especiarias.",
      verse: "João 19:38-40",
    },
  ],

  hard: [
    // dicas menos óbvias (sem “entregar”)
    {
      q: "Qual parábola Jesus contou para ensinar sobre o amor ao próximo, usando um viajante socorrido por alguém inesperado?",
      a: ["O Filho Pródigo", "O Bom Samaritano", "O Semeador", "A Ovelha Perdida"],
      c: 1,
      tip: "A lição aparece em um diálogo sobre quem é “o próximo”.",
      verse: "Lucas 10:30-37",
    },
    {
      q: "Quantos dias após o nascimento Jesus foi apresentado no templo?",
      a: ["7 dias", "8 dias", "40 dias", "80 dias"],
      c: 2,
      tip: "A resposta se conecta a um período ritual previsto na Lei para a família.",
      verse: "Lucas 2:22",
    },
    {
      q: "Quem reconheceu Jesus como o Messias quando bebê no templo?",
      a: ["Simeão e Ana", "Zacarias e Isabel", "Anás e Caifás", "Nicodemos e José"],
      c: 0,
      tip: "Duas pessoas idosas aparecem nessa cena, uma delas é descrita como profetisa.",
      verse: "Lucas 2:25-38",
    },
    {
      q: "Em qual parábola Jesus fala sobre um homem que tinha dois filhos e o mais novo pediu sua herança?",
      a: ["O Bom Samaritano", "O Semeador", "O Filho Pródigo", "Os Talentos"],
      c: 2,
      tip: "É uma história de partida, queda e retorno — e um irmão que se incomoda.",
      verse: "Lucas 15:11-32",
    },
    {
      q: "Quantas vezes Jesus disse que devemos perdoar nosso irmão?",
      a: ["7 vezes", "70 vezes", "77 vezes", "70 vezes 7"],
      c: 3,
      tip: "A resposta vem como ampliação forte de um número “já alto” sugerido por Pedro.",
      verse: "Mateus 18:21-22",
    },
    {
      q: "Quais mandamentos Jesus resumiu em dois como os maiores?",
      a: ["Amar a Deus e ao próximo", "Não matar e não roubar", "Orar e jejuar", "Crer e batizar"],
      c: 0,
      tip: "Um vem do Shema; o outro é um princípio ético sobre o próximo.",
      verse: "Mateus 22:37-40",
    },
    {
      q: "Qual parábola fala de um homem que encontrou um tesouro escondido em um campo?",
      a: ["O Semeador", "O Tesouro Escondido", "A Pérola de Grande Valor", "Os Talentos"],
      c: 1,
      tip: "É uma parábola bem curta sobre abrir mão de tudo por algo maior.",
      verse: "Mateus 13:44",
    },
    {
      q: "Qual foi o sinal que Jesus mencionou quando pediram um milagre (sinal dado aos fariseus)?",
      a: ["O sinal de Jonas", "O sinal de Moisés", "O sinal de Elias", "O sinal de Davi"],
      c: 0,
      tip: "O exemplo envolve um profeta e um período simbólico de dias.",
      verse: "Mateus 12:39-40",
    },
    {
      q: "Em qual língua estava escrita a inscrição na cruz de Jesus, segundo João?",
      a: ["Apenas em hebraico", "Apenas em latim", "Hebraico, grego e latim", "Aramaico e grego"],
      c: 2,
      tip: "O texto destaca que pessoas de vários lugares poderiam ler.",
      verse: "João 19:20",
    },
    {
      q: "Quantas bem-aventuranças aparecem em Mateus 5:3–10?",
      a: ["5", "7", "8", "10"],
      c: 2,
      tip: "Considere apenas o bloco que vai até “porque deles é o Reino dos céus”.",
      verse: "Mateus 5:3-10",
    },
  ],

  veryhard: [
    {
      q: "Qual profeta do Antigo Testamento é frequentemente associado às profecias do “Servo Sofredor” relacionadas a Jesus?",
      a: ["Isaías", "Elias", "Jonas", "Amós"],
      c: 0,
      tip: "Pense no capítulo que descreve alguém “traspassado” e “moído”.",
      verse: "Isaías 53",
    },
    {
      q: "Qual era o nome do sumo sacerdote que presidiu o julgamento religioso de Jesus, segundo os evangelhos?",
      a: ["Anás", "Caifás", "Gamaliél", "Zacarias"],
      c: 1,
      tip: "Um outro sacerdote aparece primeiro, mas o julgamento principal segue adiante.",
      verse: "João 18:13-14",
    },
    {
      q: "Em qual festa judaica Jesus entrou em Jerusalém sendo aclamado (episódio dos ramos)?",
      a: ["Páscoa", "Hanucá", "Pentecostes", "Purim"],
      c: 0,
      tip: "A multidão cita “Hosana” e a cidade está cheia de peregrinos.",
      verse: "João 12:12-13",
    },
    {
      q: "Qual discípulo era irmão de Pedro?",
      a: ["Tiago", "João", "André", "Filipe"],
      c: 2,
      tip: "Foi ele quem primeiro seguiu Jesus em João 1 e depois chamou o irmão.",
      verse: "João 1:40-41",
    },
    {
      q: "Quem foi o governador romano que condenou Jesus à crucificação?",
      a: ["Herodes", "César Augusto", "Pôncio Pilatos", "Tibério"],
      c: 2,
      tip: "Ele aparece em todos os evangelhos na cena do julgamento romano.",
      verse: "João 18:29-31",
    },
    {
      q: "Qual discípulo Jesus chamou de 'a pedra'?",
      a: ["João", "Tiago", "Pedro", "André"],
      c: 2,
      tip: "A fala ocorre após uma confissão sobre quem Jesus é.",
      verse: "Mateus 16:18",
    },
    {
      q: "Quem eram os dois profetas que apareceram com Jesus durante a transfiguração?",
      a: ["Abraão e Moisés", "Moisés e Elias", "Elias e Eliseu", "Isaías e Jeremias"],
      c: 1,
      tip: "Um representa a Lei e o outro os Profetas nas leituras tradicionais.",
      verse: "Lucas 9:30",
    },
    {
      q: "Qual era o nome do pai de João Batista?",
      a: ["José", "Zacarias", "Simeão", "Joaquim"],
      c: 1,
      tip: "Ele ficou sem falar por um tempo antes do nascimento do filho.",
      verse: "Lucas 1:13",
    },
    {
      q: "Quantos foram os reis magos que visitaram Jesus?",
      a: ["A Bíblia não especifica", "2", "3", "4"],
      c: 0,
      tip: "A tradição popular fixou um número, mas o texto bíblico não confirma.",
      verse: "Mateus 2:1-12",
    },
    {
      q: "Em qual Evangelho encontramos a frase 'No princípio era o Verbo'?",
      a: ["Mateus", "Marcos", "Lucas", "João"],
      c: 3,
      tip: "É o evangelho com abertura mais “teológica” e simbólica.",
      verse: "João 1:1",
    },
    {
      q: "Quem foi o rei que mandou matar os meninos em Belém?",
      a: ["Herodes o Grande", "Herodes Antipas", "Pilatos", "César Augusto"],
      c: 0,
      tip: "O episódio acontece logo após a visita dos magos.",
      verse: "Mateus 2:16",
    },
    {
      q: "Qual era o nome da mãe de João Batista?",
      a: ["Maria", "Ana", "Isabel", "Rebeca"],
      c: 2,
      tip: "Ela era parente de Maria e ficou grávida em idade avançada.",
      verse: "Lucas 1:13",
    },
    {
      q: "Quantos anos a mulher com fluxo de sangue sofria antes de ser curada por Jesus?",
      a: ["7 anos", "10 anos", "12 anos", "20 anos"],
      c: 2,
      tip: "O relato destaca um número de anos bem específico e repetido.",
      verse: "Marcos 5:25",
    },
    {
      q: "Qual era a aldeia de Maria e Marta?",
      a: ["Nazaré", "Betânia", "Caná", "Emaús"],
      c: 1,
      tip: "Fica perto de Jerusalém e aparece muito no ciclo de Lázaro.",
      verse: "João 11:1",
    },
    {
      q: "Em que língua Jesus normalmente falava no cotidiano na Palestina do século I?",
      a: ["Hebraico", "Grego", "Aramaico", "Latim"],
      c: 2,
      tip: "É a língua das expressões preservadas em algumas falas (“Eli, Eli…”).",
      verse: "Mateus 27:46",
    },

    // movidas do extreme por serem difíceis, mas não “extreme”
    {
      q: "Quantos peixes foram pescados na pesca milagrosa após a ressurreição, segundo João?",
      a: ["100", "120", "144", "153"],
      c: 3,
      tip: "O texto faz questão de registrar um número exato.",
      verse: "João 21:11",
    },
    {
      q: "Quem substituiu Judas Iscariotes entre os doze apóstolos?",
      a: ["Paulo", "Barnabé", "Matias", "Silas"],
      c: 2,
      tip: "A escolha foi feita após oração e um método de decisão bem antigo.",
      verse: "Atos 1:26",
    },
    {
      q: "Qual fariseu visitou Jesus à noite e depois defendeu Jesus perante o Sinédrio?",
      a: ["Gamaliel", "Nicodemos", "José de Arimateia", "Saulo de Tarso"],
      c: 1,
      tip: "Ele aparece em João em pelo menos três momentos marcantes.",
      verse: "João 3:1-2; João 7:50",
    },
  ],

  extreme: [
    // aqui ficam as mais “detalhistas”, e as dicas NÃO entregam a resposta
    {
      q: "Em qual cidade Jesus ressuscitou o filho de uma viúva durante um cortejo fúnebre?",
      a: ["Naim", "Cafarnaum", "Betsaida", "Corazim"],
      c: 0,
      tip: "Esse milagre acontece em uma cidade pouco citada, durante um funeral.",
      verse: "Lucas 7:11-15",
    },
    {
      q: "Qual era o nome do servo do sumo sacerdote cuja orelha Pedro cortou no Getsêmani?",
      a: ["Malco", "Simão", "Judas", "Marcos"],
      c: 0,
      tip: "O Evangelho de João registra o nome dele explicitamente.",
      verse: "João 18:10",
    },
    {
      q: "Qual discípulo Jesus encontrou debaixo de uma figueira antes de chamá-lo?",
      a: ["Pedro", "Natanael (Bartolomeu)", "Mateus", "João"],
      c: 1,
      tip: "Ele faz uma das primeiras confissões fortes sobre Jesus no Evangelho de João.",
      verse: "João 1:48-49",
    },
    {
      q: "Quantos dias após a ressurreição Jesus apareceu aos discípulos pela terceira vez, no Mar de Tiberíades?",
      a: ["3 dias", "7 dias", "Não está especificado", "40 dias"],
      c: 2,
      tip: "O texto enumera que foi uma aparição específica, mas não dá contagem de dias.",
      verse: "João 21:1-14",
    },
    {
      q: "Qual era a profissão/condição de Simão, em cuja casa Jesus estava quando uma mulher o ungiu (em Betânia)?",
      a: ["Carpinteiro", "Leproso", "Fariseu", "Publicano"],
      c: 1,
      tip: "Ele é identificado por um “apelido”/condição, não por profissão comum.",
      verse: "Mateus 26:6",
    },
    {
      q: "Em qual sinagoga Jesus leu o texto de Isaías 61 e declarou que a escritura se cumpria?",
      a: ["Sinagoga de Cafarnaum", "Sinagoga de Nazaré", "Sinagoga de Jerusalém", "Sinagoga de Betsaida"],
      c: 1,
      tip: "Isso ocorre quando Jesus volta à cidade onde foi criado.",
      verse: "Lucas 4:16-21",
    },
    {
      q: "Em qual cidade/região da Decápolis Jesus expulsou uma legião de demônios (segundo Marcos 5:1)?",
      a: ["Gadara", "Gerasa", "Hippos", "Pela"],
      c: 1,
      tip: "Há variações de nome em manuscritos/tradições, mas Marcos registra uma forma específica.",
      verse: "Marcos 5:1",
    },
    {
      q: "Quantas vezes o evangelho de João registra Jesus chorando?",
      a: ["Uma vez", "Duas vezes", "Três vezes", "Nenhuma vez"],
      c: 0,
      tip: "A cena está ligada à morte de um amigo e a uma frase bem curta.",
      verse: "João 11:35",
    },
    {
      q: "Qual era o nome da mãe de João e Tiago, filhos de Zebedeu?",
      a: ["Maria", "Salomé", "Joana", "Susana"],
      c: 1,
      tip: "Ela aparece entre as mulheres citadas na crucificação/sepultamento em alguns relatos.",
      verse: "Mateus 27:56",
    },
    {
      q: "Em qual local Jesus curou dez leprosos?",
      a: ["Samaria", "Galileia", "Entre Samaria e Galileia", "Judeia"],
      c: 2,
      tip: "O relato destaca uma “fronteira” geográfica entre duas regiões.",
      verse: "Lucas 17:11-14",
    },
    {
      q: "Quantos dias Lázaro estava morto quando Jesus o ressuscitou?",
      a: ["1 dia", "2 dias", "3 dias", "4 dias"],
      c: 3,
      tip: "O texto enfatiza o tempo no túmulo como parte do impacto do milagre.",
      verse: "João 11:17",
    },
    {
      q: "Qual discípulo era também chamado de Tadeu?",
      a: ["Simão Zelote", "Judas (não Iscariotes)", "Matias", "Filipe"],
      c: 1,
      tip: "É um nome que pode confundir porque há outro Judas bem mais famoso no grupo.",
      verse: "Mateus 10:3",
    },
    {
      q: "Em qual parábola Jesus menciona 'trabalhadores da primeira e da última hora'?",
      a: ["Os talentos", "Os trabalhadores da vinha", "As dez virgens", "O filho pródigo"],
      c: 1,
      tip: "A história gira em torno de pagamento igual para horários diferentes.",
      verse: "Mateus 20:1-16",
    },
    {
      q: "Quantos pães Jesus usou para alimentar quatro mil pessoas?",
      a: ["5 pães", "7 pães", "12 pães", "20 pães"],
      c: 1,
      tip: "Não é o mesmo número do milagre dos cinco mil.",
      verse: "Marcos 8:5-9",
    },
    {
      q: "Qual era o nome do centurião romano cuja fé impressionou Jesus?",
      a: ["Cornélio", "A Bíblia não menciona seu nome", "Júlio", "Cláudio"],
      c: 1,
      tip: "Ele é conhecido pelo episódio, mas o texto não registra seu nome próprio.",
      verse: "Mateus 8:5-10",
    },
  ],
};
